### ISSUE TITLE
The name

### ISSUE THREAD

**Issue by ellenkorbes** [kris-nova/transfigure#2]
A few days back I and Kris provisionally came up with `transfigure.io`, but now as a team we need to decide on a permanent name.

I hope we can agree on:

- Using a name that makes sense to non-native English speakers (so no cryptic local slang).

- Avoiding -ly and -ing terminations.

**Comment by ellenkorbes** [comment]
So far the suggestions are:

The initial name:

- transfigure.io

These suggestions by cora:

- lime.rocks
- lime.news
- ~cherry.red~
- kiwiplace.org
- lime.place
- melon.city 
- ~watermelon.io~
- peach.house
- ~oranges.io~
- pineapple.news
- ~lime.io~
- lime.care
- ~apples.io~
- redapple.org
- citrus.house
- Catte.us 
- Land.media
- ~Support.io~
- ~Landing.io~
- ~Map.io~
- Pathforus.com
- Truelife.io
- Trueway.io

(The crossed out domains are not available.)

**Comment by ellenkorbes** [comment]
Please include all your suggestions by Friday, June 16 :)

**Comment by kris-nova** [comment]
1. `transfigure.io`
2. `pathforus.com`
3. `melon.city` IDK why but I love this

**Comment by ellenkorbes** [comment]
Here are a few more suggestions:

- genderidentity.io
- trans.coffee
- trueself.io
- transplural.com
- multipath.io (5th Element anyone? :)

**Comment by ellenkorbes** [comment]
My vote:

1. genderidentity.io
2. trans.coffee
3. transfigure.io

**Comment by renatap** [comment]
1. transplural.com
2. trans.coffee
3. genderidentity.io

**Comment by mrxinu** [comment]
1. `genderidentity.io`
2. `trueself.io`
3. `transfigure.io`

**Comment by swarnap** [comment]
trueself.io
truelife.io

**Comment by ellenkorbes** [comment]
The top voted ones are:

-` genderidentity.io` 3
-` transfigure.io` 3
-` trans.coffee` 2
-` trueself.io`  2

So now we choose between the top two, `genderidentity.io` and` transfigure.io`.

**Comment by ellenkorbes** [comment]
My vote goes to `genderidentity.io`.

**Comment by mrxinu** [comment]
I vote for `genderidentity.io`.

**Comment by kris-nova** [comment]
As much as I love trueself and truelife.. I think genderidentity.io will market better.. but curious what our marketing expert @swarnap has to say

**Comment by ellenkorbes** [comment]
`genderidentity.io` !
